### ISSUE TITLE
DeprecationWarning somewhere hidden

### ISSUE THREAD

**Issue by pvanagtmaal** [alorence/django-modern-rpc#1]
Hi, I am using your app (love it) for a week or so, however I would really like to get rid of the following message I get as soon as I add the app to my `INSTALLED_APPS` list:

```~/.virtualenvs/env/lib/python3.5/site-packages/django/contrib/auth/base_user.py:52: 
DeprecationWarning: __class__ not set defining 'AbstractBaseUser' as <class 'django.contrib.auth.base_user.AbstractBaseUser'>. Was __classcell__ propagated to type.__new__?
  class AbstractBaseUser(models.Model):
```

I have tried to seek for myself where it's coming from but I cannot seem to find it.

My requirements.txt:

```
appdirs==1.4.0
Django==1.10.5
django-modern-rpc==0.4.2
mysqlclient==1.3.9
packaging==16.8
pyparsing==2.1.10
six==1.10.0
```

Do you know where it's coming from and how it can be fixed?

Thanks!

**Comment by alorence** [comment]
Hi and thank you for your support.

It is the first time I see this error message, I have no idea where it come from. What version of Python are you using for this particular project ?

**Comment by pvanagtmaal** [comment]
I am using python3.5

**Comment by alorence** [comment]
I just created a new virtualenv and a clean project, installing only the packages from the list you provided, and I can't see this warning.

The only package I couldn't install was mysqlclient since I am on Windows. Can you try to reproduce this issue in a clean project and verify if the warning is still displayed when mysqlclient is not installed ?

Can you tell which OS you are working on ?

This issue sounds very strange, since the project doesn't use Django user model at all (at least in version 0.4.2, since authentication is not yet supported). Can you try to provide as most information as you can. In particular, do you have any stacktrace or file / line number reference that could help to locate the origin ?

**Comment by pvanagtmaal** [comment]
Ok my bad... I'm on OS X and I have multiple versions of python installed:

- 2.7 for OS X
- 3.5 for Django
- 3.6 for new stuff

Unfortunately I did not notice the 3.6 install has overwritten the python3 symlink so I was using 3.6 instead of 3.5. Using the corrected python3 in a fresh virtual environment caused the message to vanish.

Thanks for your time and keep up the good work!
