### ISSUE TITLE
JSON-RPC specification not fully implemnted in context of exception raised with data

### ISSUE THREAD

**Issue by nikitinsm** [alorence/django-modern-rpc#10]
NOTE: More feature than bug

http://www.jsonrpc.org/specification#error_object
There is a data param but for now it is impossible to through `RPCException` with data attributes that will be passed to response body. Workaround is implementing your own `JSONRPCHandler` with `result_error` override.

**Comment by alorence** [comment]
As you noticed, in the standard, the `data` member "may be omitted". Since the library was designed to be compatible with both JSON-RPC and XML-RPC (which did not provide such a level of error reporting), I decided to not implement this attribute in RPC exceptions.

But I agree, at some point, the library should be flexible enough to let users return data when exception are raised. I will take a few time to think to a proper solution and will publish a new version when this feature will be implemented.

Thank you for your feedback !

**Comment by nikitinsm** [comment]
Thanks a lot!
