### ISSUE TITLE
Does not install markdown

### ISSUE THREAD

**Issue by samlobel** [alorence/django-modern-rpc#16]
For some reason, the library does not install Markdown when installed through Pip. I found this out by settign my MODERNRPC_DOC_FORMAT to markdown.

Other than that, great library

**Comment by alorence** [comment]
Hi there, and thank you for the feedback,

Indeed, `markdown` is not automatically installed with `django-modern-rpc` because it is an optional dependency. You will need markdown package only if you write documentation for your RPC methods with Markdown syntax. You can also decide to write it with reStructured syntax. In such case, you will need to install `docutils`.

In both case, you have to set `settings.MODERNRPC_DOC_FORMAT` with value `rst` or `md` to determine which parser will be used to transform methods documentation into HTML.
Please check https://github.com/alorence/django-modern-rpc/blob/master/modernrpc/core.py#L167 to see how it works. Note that either `docutils.core` or `markdown` are imported only depending on value of `settings.MODERNRPC_DOC_FORMAT`. By default, the variable is empty, which means no particular parser is used to convert method doc to HTML:

```python
return "<p>{}</p>".format(docstring.replace('\n\n', '</p><p>').replace('\n', ' '))
```

For the record, the setting value is documented here : http://django-modern-rpc.readthedocs.io/en/latest/basic_usage/settings.html#modernrpc-doc-format

I think the behavior is OK for most of the case, but I agree on one point, the documentation should be more clear about that point. I'll modify it to explicitely state that additional dependency must be installed in such cases.

**Comment by alorence** [comment]
Hi Sam,

The documentation has been updated to prepare for next release.

Use of reStructuredText or Markdown in RPC methods docstring is now clearly explained. In addition, the doc clearly state the corresponding additional package need to be instlled in such case.

Please see http://django-modern-rpc.readthedocs.io/en/latest/configuration_guide/auto_generated_documentation.html#write-documentation
