### ISSUE TITLE
support "application/json-rpc" as content type

### ISSUE THREAD

**Issue by dansan** [alorence/django-modern-rpc#24]
The jsonrpclib (https://github.com/joshmarshall/jsonrpclib/) uses for client requests the content type ``application/json-rpc``. That doesn't work with django-modern-rpc.

The JSON-RPC 2.0 specification doesn't specify a content type, but the [1.2 spec](https://www.jsonrpc.org/historical/json-rpc-over-http.html) (for transport over HTTP) says:
> Content-Type SHOULD be 'application/json-rpc' but MAY be 'application/json' or 'application/jsonrequest'

So I think it'd be OK, to accept those  too.

**Comment by alorence** [comment]
Thank you for your contribution, this is highly appreciated. I agree that following the links you provided, these 2 content-type values should be accepted too. I totally missed this part of the spec, since I used the [2.0 specification](https://www.jsonrpc.org/specification) to build the library.

I will merge your work as soon as I have a few time to push a new release. In addition, I want to add 1 or 2 unit tests to cover the requests received with these headers. This will ensure no regression will eventually break this in the future. You will be noticed when this will be done.

I am a bit busy these days, so I will do it ASAP, but you will have to be patient ;) Thanks again for taking time to contribute.

**Comment by dansan** [comment]
Thank you, that's great to hear.
I'll have to write some tests for my site as well, so I'll take a peak at how you do it :)
