### ISSUE TITLE
Silent warning on load

### ISSUE THREAD

**Issue by luzik** [alorence/django-modern-rpc#34]
I got this

Warning: Unable to load module "api.rpc_methods" declared in settings.MODERNRPC_METHODS_MODULES. Please ensure it is available and doesn't contain any error

and no trace with logger configured to handle modernrpc.

I believe this should be critical error with trace back and exit, as it would be with bug in Django view. Or even better, such exceptions should not be handled by Django-modern-rpc at all. This is not runtime exception like while calling rpc - where it is ok to intercept exception and return error in json-rpm response. This is start up error, so while developing app I have to immediately know where the bug is.

**Comment by alorence** [comment]
Hello,

Thank you very much for your feedback.
Indeed when a RPC methods module contain errors, they are not directly printed on load. Instead a warning message is displayed. This was originally designed to ensure the project can still start when 1 or more module cannot be imported (because they are missing). I understand that this behavior may lead to unconfortable situations, when you cannot directly see what is causing the ImportError.

I recently started to rewrite some parts of the library in order to publish a stable v1.0 in the next weeks. I will include this issue in this future release. Unfortunately, I cannot publish a hotfix minor release with that since it may break existing code.

If you really need to get a traceback on load when your modules contain errors, you may try to install the library from the branch "issue_34". It was just pushed (Unit tests are running: https://travis-ci.org/github/alorence/django-modern-rpc/builds/761938544)

Feel free to answer here if you have another idea on how that issue could be addressed.

Regards

**Comment by luzik** [comment]
Thank You for such a quick response.

**Comment by alorence** [comment]
Hi,

For your information, the last pre-release 1.0.0a1 includes some changes on lib startup. Errors with `settings.MODERNRPC_METHODS_MODULES` are now displayed using Django check system. In addition, any invalid module will raise an exception when it is imported. The goal is to provide as much information as possible and prevent common errors (module not found, synxtax error in a module, etc.)

If you have a few minutes, maybe you could try this and provide feedback? I would like to publish a final 1.0.0 after ensuring everything works fine for all users.
