### ISSUE TITLE
Implementing a simple rest endpoint; POSTMAN returns no data

### ISSUE THREAD

**Issue by Coldsp33d** [alorence/django-modern-rpc#40]
Following the documentation, I have implemented a simple rpc method 

```
@rpc_method
def content_type_printer(**kwargs):

    # Get the current request
    request = kwargs.get(REQUEST_KEY)

    # Other available objects are:
    # protocol = kwargs.get(PROTOCOL_KEY)
    # entry_point = kwargs.get(ENTRY_POINT_KEY)
    # handler = kwargs.get(HANDLER_KEY)

    # Return the content-type of the current request
    return request.META.get('Content-Type', '')
```

However when I try making a POST request to the /rpc endpoint, the request succeeds but nothing is returned. What am I missing here?

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/HzHGW.png

**Comment by alorence** [comment]
Hi,

There is 2 issues in your example.

First, you sent a JSON-RPC request without any "id". This is handled as a "notification" request (see https://www.jsonrpc.org/specification#request_object) that's why you get a 204 status with no data in response. Simply add `"id": 1` in your request body to get a proper response.

Second, in the rpc_method, you used `request.META.get('Content-Type', '')` to extract the content-type value from incoming request. This is a brand old way to get Content-Type and is not supported anymore by Django API. The correct way with recent Django versions is `request.content_type`. I assume this should be updated in the documentation, as it has not been updated since years now.

Please let me know if you need additional information.

Regards

**Comment by Coldsp33d** [comment]
Thank you @alorence ! That worked well! And thank you for this reference: https://www.jsonrpc.org/specification#request_object

I had been looking for a long time on how to call a parameterized rpc function and this was helpful!
