### ISSUE TITLE
HTTP response code in case of error response

### ISSUE THREAD

**Issue by mlembke** [alorence/django-modern-rpc#53]
Hi, I skimmed through JSON-RPC specification that it is linked in the docs, but I didn't find anything about HTTP status code in case of error response. I guess the assumption there was that it’s transport layer agnostic, but we use Django and HTTP as transport here and I noticed that the HTTP status code is always 200, even when I raise exception and error response is returned to the client.

So, my question is: should it be this way, or error response should have other status code? The way it is now, the client always has to check the response's body and search for "error" key. Would I break the specification if I changed it to return let’s say 4XX status code?
And the second question: what would be the best way to implement such a change on my side? My first thought is to write a simple middleware that would change the status code in the error response.

**Comment by alorence** [comment]
Hi, and thank you for your feedback.

You are right, [JSON-RPC specs](https://www.jsonrpc.org/specification#response_object) does ot provide information about status code to return. But [XML-RPC spec](http://xmlrpc.com/spec.md) does:
> Unless there's a lower-level error, always return 200 OK.

For consistency between XML-RPC and JSON-RPC, this library always return a 200 status, even when an error is returned.

Before 1.0 version, there were an exception. The library returned a 403 on authentication error. This was problematic because
1. That did not respect the XML-RPC standard
2. The returned code was 403 for a single request with auth error, but was still 200 for unauthenticated request in the middle of a multicall (XML-RPC) or batch request (JSON-RPC)
For those reasons, the behavior was changed in 1.0 (see https://django-modern-rpc.readthedocs.io/en/latest/changelog.html#breaking-changes)

If you really need to return a different status in some case, you may succeed by writing a custom middleware, as you suggested. But if you do so, you may break the compatibility with some clients, in particular XML-RPC ones. And you will need to choose which status code to return when a single call raise an exception in a middle of a multicall or batch.

**Comment by mlembke** [comment]
Thank you for answering so quickly. And for the package of course :)

Ok, my app doesn't allow for XML-RPC, only JSON-RPC is supported, so I guess it should be fine and I don't go against the JSON-RPC spec if I change status codes since, as you also also noticed, there is no restrictions in JSON-RPC spec on what HTTP response code should be.

The only problem could be batch/multicall, but I'll try to figure something out.

I guess you can close the issue. Thanks.
