### ISSUE TITLE
Tries to install Django 1.11. Why?

### ISSUE THREAD

**Issue by shamanis** [alorence/django-modern-rpc#6]
In setup.py:

```python
install_requires=[
        "Django>=1.8.0",
]
```

In env installed Django 1.10.7. Run pip install django-modern-rpc - tries to install Django 1.11.

Why?

**Comment by alorence** [comment]
Hi Petr,

This is strange, I just tried to reproduce the described issue, but I didn't see the same behavior:

```bash
~ ᐅ virtualenv -p python3 test_issue_6
Running virtualenv with interpreter /usr/local/bin/python3
Using base prefix '/usr/local'
New python executable in /home/alorence/test_issue_6/bin/python3
Also creating executable in /home/alorence/test_issue_6/bin/python
Installing setuptools, pip, wheel...done.

~ ᐅ source test_issue_6/bin/activate

(test_issue_6) ~ ᐅ pip install Django==1.10.7
Collecting Django==1.10.7
  Downloading Django-1.10.7-py2.py3-none-any.whl (6.8MB)
    100% |████████████████████████████████| 6.8MB 153kB/s
Installing collected packages: Django
Successfully installed Django-1.10.7

(test_issue_6) ~ ᐅ pip install django-modern-rpc
Collecting django-modern-rpc
  Downloading django_modern_rpc-0.6.0-py2.py3-none-any.whl
Requirement already satisfied: Django>=1.8.0 in ./test_issue_6/lib/python3.6/site-packages (from django-modern-rpc)
Installing collected packages: django-modern-rpc
Successfully installed django-modern-rpc-0.6.0

(test_issue_6) ~ ᐅ pip freeze
appdirs==1.4.3
Django==1.10.7
django-modern-rpc==0.6.0
packaging==16.8
pyparsing==2.2.0
six==1.10.0
```

I got the same result on linux and windows. Basically, the statement `install_requires=["Django>=1.8.0"]` in setup.py ensure django-modern-rpc is installed in an environment with at least django 1.8.

If installing django-moder-rpc installed django 1.11, this is mostly because you installed the package in an environment where django were NOT previously installed. Can you doucle check that ?

**Comment by alorence** [comment]
Hi @shamanis,

Do you have additional info on this issue ? You were the first to report it, but the `install_requires` section in setup.py is used since the very first version of the package (see 4588eebf7e3e). Can you still reproduce the issue ?
